name: isotope_auth_mock
description: Mock authentication service for testing Isotope apps.
version: 1.0.0
homepage: https://github.com/isotope-studio/isotope_auth_mock

publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.3
  isotope_auth:
    git: git://github.com/isotopeltd/isotope_auth.git
    version: ^1.0.0
  random_string: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
